#page title
page_title                                : Replica Forex                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# Information About Yourself
your_name                                 : Replica Economics                               
your_link                                 : https://emilbaehr.com                     
your_city                                 : Copenhagen                                
email_address                             : emil.baehr@gmail.com
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : emilbaehr
youtube_username                          :


# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://exchange.pancakeswap.finance/#/swap        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/RFX_logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Replica Forex Token                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The First Binance Smart Chain Token based on Foreign Exchange Automated Trading Software. Available on PancakeSwap! 

enable_smart_app_banner                   :                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Automated Trading Software
    description                           : As the MT4 software market remains competitive, the GPS Forex Robot has withstood the test of time. [Click Here](https://gpsforexrobot.com/) for more information. 
    fontawesome_icon_name                 : code
    
  - title                                 : Shared Community Pool
    description                           : Less risk, more reward is our objective! RFX Holders will benefit consistently from Forex yield profits.  
    fontawesome_icon_name                 : users

  - title                                 : Replica Market Management
    description                           : Many crypto projects fail due to lack of market management. Our team has a management system for market health retention.
    fontawesome_icon_name                 : chart-line

  - title                                 : Independent
    description                           : Because RFX is Forex related, dependence on community growth isn't necessary due to the win percentage of the automated trading software.
    fontawesome_icon_name                 : fist-raised

  - title                                 : Live Updates
    description                           : Notifications regarding Forex trades will be per trade event(e.g. open trades, closed trades, etc.). All updates will be available on our social media.
    fontawesome_icon_name                 : comment
  
  - title                                 : Short & Long Term
    description                           : Regardless of your strategy, RFX has the flexibility to suit everyone's financial goals. 
    fontawesome_icon_name                 : coins

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/Beach.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
